# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "StarGit"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

graph:
  attributes:
    country:
      label: Country
      type: Str
      values:
        default: 0xA3A3A3
        "United States": 0x5100FF
        "United Kinddom": 0x00AAFF
        Germany: 0x856508
        Canada: 0xD5B2D9
        Brazil: 0x37A339
        France: 0xE391E3
        Japan: 0xFF0000
        Russia: 0xFF9100
    language:
      label: Language
      type: Str
      values:
        Ruby: 0xE32726
        C: 0x171C3F
        Python: 0x5BAC29
        Other: 0xA6347F
        JavaScript: 0x367FA5
        Perl: 0x364493
        PHP: 0x82A635
        JVM: 0x763C8D
        default: 0xdddddd
    degree:
      label: Contributions
      type: Num
      colorMin:  0xFF0000
      colorMax: 0xFFCCCC
      default: 0xFA7070
    followers_count:
      label: Followers
      type: Num
      colorMin: 0x03A16A
      colorMax: 0xB1E3D1
      default: 0xFA7070
    indegree:
      label: InDegree
      type: Num
      colorMin: 0x120087
      colorMax: 0x9F93ED
      default: 0xFA7070
